export const SupportedIntransitiveMethods = [
  "and",
  "any",
  "as",
  "barrier",
  "by",
  "cap",
  "coalesce",
  "coin",
  "count",
  "dedup",
  //" difference",
  //" disjunct",
  //" element",
  //" elementMap",
  //" emit",
  //" explain",
  "map",
  "flatMap",
  "fold",
  "fold",
  "from",
  "from",
  //" group",
  //" groupCount",
  "has",
  "hasId",
  "hasKey",
  "identity",
  //" index",
  //" inject",
  //" intersect",
  //" is",
  //" key",
  //" label",
  //" length",
  //" limit",
  //" loops",
  //" ltrim",
  //" map",
  //" match",
  //" math",
  //" max",
  //" mean",
  //" merge",
  //" mergeEdge // will not be supported",
  //" mergeVertex // will not be supported",
  //" min",
  //" none",
  //" not",
  //" option",
  //" optional",
  //" or",
  //" order step",
  //" pagerank",
  //" path",
  //" peerPressure",
  //" product",
  //" profile",
  //" project",
  //" program",
  //" properties",
  //" property",
  //" propertyMap",
  //" range",
  //" read",
  //" repeat",
  //" replace",
  //" reverse",
  //" rtrim",
  //" sack",
  //" select",
  //" shortestPath",
  "sideEffect",
  //" skip",
  //" split",
  //" subgraph",
  //" substring",
  //" sum",
  //" tail",
  //" timeLimit",
  //" to",
  //" toLower",
  //" toUpper",
  //" tree",
  //" trim",
  //" unfold",
  //" union",
  //" until",
  //" v",
  //" value",
  //" valueMap",
  //" values",
  //" vertex",
  "where",
  //" with",
  //" write",
];
